spring:
  profiles:
    active: dev
  cloud:
    gateway:
        routes:
          - id: product_route
            uri: lb://gulimall-product
            predicates:
              - Path=/api/product/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: third_party_route
            uri: lb://gulimall-third-party
            predicates:
              - Path=/api/thirdparty/**
            filters:
              - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

          - id: member_route
            uri: lb://gulimall-member
            predicates:
              - Path=/api/member/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: ware_route
            uri: lb://gulimall-ware
            predicates:
              - Path=/api/ware/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: admin_route
            uri: lb://renren-fast
            predicates:
              - Path=/api/**
            filters: # 这段过滤器和验证码有关，api内容缓存了/renren-fast，还得注意/renren-fast也注册到nacos中
              - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

          - id: gulimall_host
            uri: lb://gulimall-product
            predicates:
              - Host=yuanmall.top

          - id: gulimall_search_host
            uri: lb://gulimall-search
            predicates:
              - Host=search.yuanmall.top

  application:
    name: gulimall-gateway

server:
  port: 88
